// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package proto

import (
	flatbuffers "github.com/google/flatbuffers/go"
	"strconv"
)

type Realm byte

const (
	RealmPlayer   Realm = 0
	RealmDesigner Realm = 1
)

var EnumNamesRealm = map[Realm]string{
	RealmPlayer:   "Player",
	RealmDesigner: "Designer",
}

var EnumValuesRealm = map[string]Realm{
	"Player":   RealmPlayer,
	"Designer": RealmDesigner,
}

func (v Realm) String() string {
	if s, ok := EnumNamesRealm[v]; ok {
		return s
	}
	return "Realm(" + strconv.FormatInt(int64(v), 10) + ")"
}

type ClientKind byte

const (
	ClientKindWeb ClientKind = 0
	ClientKindIOS ClientKind = 1
)

var EnumNamesClientKind = map[ClientKind]string{
	ClientKindWeb: "Web",
	ClientKindIOS: "IOS",
}

var EnumValuesClientKind = map[string]ClientKind{
	"Web": ClientKindWeb,
	"IOS": ClientKindIOS,
}

func (v ClientKind) String() string {
	if s, ok := EnumNamesClientKind[v]; ok {
		return s
	}
	return "ClientKind(" + strconv.FormatInt(int64(v), 10) + ")"
}

type Verb uint16

const (
	VerbNone            Verb = 0
	VerbJoinMap         Verb = 1
	VerbLeaveMap        Verb = 2
	VerbMove            Verb = 3
	VerbInteract        Verb = 4
	VerbAction          Verb = 5
	VerbSpectate        Verb = 6
	VerbDesignerCommand Verb = 7
	VerbHeartbeat       Verb = 8
	VerbAckTick         Verb = 9
)

var EnumNamesVerb = map[Verb]string{
	VerbNone:            "None",
	VerbJoinMap:         "JoinMap",
	VerbLeaveMap:        "LeaveMap",
	VerbMove:            "Move",
	VerbInteract:        "Interact",
	VerbAction:          "Action",
	VerbSpectate:        "Spectate",
	VerbDesignerCommand: "DesignerCommand",
	VerbHeartbeat:       "Heartbeat",
	VerbAckTick:         "AckTick",
}

var EnumValuesVerb = map[string]Verb{
	"None":            VerbNone,
	"JoinMap":         VerbJoinMap,
	"LeaveMap":        VerbLeaveMap,
	"Move":            VerbMove,
	"Interact":        VerbInteract,
	"Action":          VerbAction,
	"Spectate":        VerbSpectate,
	"DesignerCommand": VerbDesignerCommand,
	"Heartbeat":       VerbHeartbeat,
	"AckTick":         VerbAckTick,
}

func (v Verb) String() string {
	if s, ok := EnumNamesVerb[v]; ok {
		return s
	}
	return "Verb(" + strconv.FormatInt(int64(v), 10) + ")"
}

type SpectateMode byte

const (
	SpectateModeFreeCam      SpectateMode = 0
	SpectateModeFollowPlayer SpectateMode = 1
)

var EnumNamesSpectateMode = map[SpectateMode]string{
	SpectateModeFreeCam:      "FreeCam",
	SpectateModeFollowPlayer: "FollowPlayer",
}

var EnumValuesSpectateMode = map[string]SpectateMode{
	"FreeCam":      SpectateModeFreeCam,
	"FollowPlayer": SpectateModeFollowPlayer,
}

func (v SpectateMode) String() string {
	if s, ok := EnumNamesSpectateMode[v]; ok {
		return s
	}
	return "SpectateMode(" + strconv.FormatInt(int64(v), 10) + ")"
}

type DesignerOpcode uint16

const (
	DesignerOpcodeNone              DesignerOpcode = 0
	DesignerOpcodeSpawnAny          DesignerOpcode = 1
	DesignerOpcodeSetResource       DesignerOpcode = 2
	DesignerOpcodeTakeControlEntity DesignerOpcode = 3
	DesignerOpcodeReleaseControl    DesignerOpcode = 4
	DesignerOpcodeTeleport          DesignerOpcode = 5
	DesignerOpcodeFreezeTick        DesignerOpcode = 6
	DesignerOpcodeStepTick          DesignerOpcode = 7
	DesignerOpcodeGodmode           DesignerOpcode = 8
	DesignerOpcodePlaceTiles        DesignerOpcode = 200
	DesignerOpcodeEraseTiles        DesignerOpcode = 201
	DesignerOpcodePlaceLighting     DesignerOpcode = 202
)

var EnumNamesDesignerOpcode = map[DesignerOpcode]string{
	DesignerOpcodeNone:              "None",
	DesignerOpcodeSpawnAny:          "SpawnAny",
	DesignerOpcodeSetResource:       "SetResource",
	DesignerOpcodeTakeControlEntity: "TakeControlEntity",
	DesignerOpcodeReleaseControl:    "ReleaseControl",
	DesignerOpcodeTeleport:          "Teleport",
	DesignerOpcodeFreezeTick:        "FreezeTick",
	DesignerOpcodeStepTick:          "StepTick",
	DesignerOpcodeGodmode:           "Godmode",
	DesignerOpcodePlaceTiles:        "PlaceTiles",
	DesignerOpcodeEraseTiles:        "EraseTiles",
	DesignerOpcodePlaceLighting:     "PlaceLighting",
}

var EnumValuesDesignerOpcode = map[string]DesignerOpcode{
	"None":              DesignerOpcodeNone,
	"SpawnAny":          DesignerOpcodeSpawnAny,
	"SetResource":       DesignerOpcodeSetResource,
	"TakeControlEntity": DesignerOpcodeTakeControlEntity,
	"ReleaseControl":    DesignerOpcodeReleaseControl,
	"Teleport":          DesignerOpcodeTeleport,
	"FreezeTick":        DesignerOpcodeFreezeTick,
	"StepTick":          DesignerOpcodeStepTick,
	"Godmode":           DesignerOpcodeGodmode,
	"PlaceTiles":        DesignerOpcodePlaceTiles,
	"EraseTiles":        DesignerOpcodeEraseTiles,
	"PlaceLighting":     DesignerOpcodePlaceLighting,
}

func (v DesignerOpcode) String() string {
	if s, ok := EnumNamesDesignerOpcode[v]; ok {
		return s
	}
	return "DesignerOpcode(" + strconv.FormatInt(int64(v), 10) + ")"
}

type Auth struct {
	_tab flatbuffers.Table
}

func GetRootAsAuth(buf []byte, offset flatbuffers.UOffsetT) *Auth {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Auth{}
	x.Init(buf, n+offset)
	return x
}

func FinishAuthBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsAuth(buf []byte, offset flatbuffers.UOffsetT) *Auth {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Auth{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedAuthBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Auth) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Auth) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Auth) ProtocolVersion(obj *ProtocolVersion) *ProtocolVersion {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(ProtocolVersion)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *Auth) Realm() Realm {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return Realm(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *Auth) MutateRealm(n Realm) bool {
	return rcv._tab.MutateByteSlot(6, byte(n))
}

func (rcv *Auth) Token() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Auth) ClientKind() ClientKind {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return ClientKind(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *Auth) MutateClientKind(n ClientKind) bool {
	return rcv._tab.MutateByteSlot(10, byte(n))
}

func (rcv *Auth) ClientVersion() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func AuthStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func AuthAddProtocolVersion(builder *flatbuffers.Builder, protocolVersion flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(protocolVersion), 0)
}
func AuthAddRealm(builder *flatbuffers.Builder, realm Realm) {
	builder.PrependByteSlot(1, byte(realm), 0)
}
func AuthAddToken(builder *flatbuffers.Builder, token flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(token), 0)
}
func AuthAddClientKind(builder *flatbuffers.Builder, clientKind ClientKind) {
	builder.PrependByteSlot(3, byte(clientKind), 0)
}
func AuthAddClientVersion(builder *flatbuffers.Builder, clientVersion flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(clientVersion), 0)
}
func AuthEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
type ClientMessage struct {
	_tab flatbuffers.Table
}

const ClientMessageIdentifier = "BLIN"

func GetRootAsClientMessage(buf []byte, offset flatbuffers.UOffsetT) *ClientMessage {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ClientMessage{}
	x.Init(buf, n+offset)
	return x
}

func FinishClientMessageBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	identifierBytes := []byte(ClientMessageIdentifier)
	builder.FinishWithFileIdentifier(offset, identifierBytes)
}

func ClientMessageBufferHasIdentifier(buf []byte) bool {
	return flatbuffers.BufferHasIdentifier(buf, ClientMessageIdentifier)
}

func GetSizePrefixedRootAsClientMessage(buf []byte, offset flatbuffers.UOffsetT) *ClientMessage {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ClientMessage{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedClientMessageBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	identifierBytes := []byte(ClientMessageIdentifier)
	builder.FinishSizePrefixedWithFileIdentifier(offset, identifierBytes)
}

func SizePrefixedClientMessageBufferHasIdentifier(buf []byte) bool {
	return flatbuffers.SizePrefixedBufferHasIdentifier(buf, ClientMessageIdentifier)
}

func (rcv *ClientMessage) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ClientMessage) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ClientMessage) Verb() Verb {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return Verb(rcv._tab.GetUint16(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *ClientMessage) MutateVerb(n Verb) bool {
	return rcv._tab.MutateUint16Slot(4, uint16(n))
}

func (rcv *ClientMessage) Payload(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *ClientMessage) PayloadLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *ClientMessage) PayloadBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ClientMessage) MutatePayload(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func ClientMessageStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func ClientMessageAddVerb(builder *flatbuffers.Builder, verb Verb) {
	builder.PrependUint16Slot(0, uint16(verb), 0)
}
func ClientMessageAddPayload(builder *flatbuffers.Builder, payload flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(payload), 0)
}
func ClientMessageStartPayloadVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func ClientMessageEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
type JoinMapPayload struct {
	_tab flatbuffers.Table
}

func GetRootAsJoinMapPayload(buf []byte, offset flatbuffers.UOffsetT) *JoinMapPayload {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &JoinMapPayload{}
	x.Init(buf, n+offset)
	return x
}

func FinishJoinMapPayloadBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsJoinMapPayload(buf []byte, offset flatbuffers.UOffsetT) *JoinMapPayload {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &JoinMapPayload{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedJoinMapPayloadBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *JoinMapPayload) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *JoinMapPayload) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *JoinMapPayload) MapId() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *JoinMapPayload) MutateMapId(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func (rcv *JoinMapPayload) InstanceHint() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func JoinMapPayloadStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func JoinMapPayloadAddMapId(builder *flatbuffers.Builder, mapId uint32) {
	builder.PrependUint32Slot(0, mapId, 0)
}
func JoinMapPayloadAddInstanceHint(builder *flatbuffers.Builder, instanceHint flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(instanceHint), 0)
}
func JoinMapPayloadEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
type LeaveMapPayload struct {
	_tab flatbuffers.Table
}

func GetRootAsLeaveMapPayload(buf []byte, offset flatbuffers.UOffsetT) *LeaveMapPayload {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &LeaveMapPayload{}
	x.Init(buf, n+offset)
	return x
}

func FinishLeaveMapPayloadBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsLeaveMapPayload(buf []byte, offset flatbuffers.UOffsetT) *LeaveMapPayload {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &LeaveMapPayload{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedLeaveMapPayloadBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *LeaveMapPayload) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *LeaveMapPayload) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *LeaveMapPayload) MapId() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *LeaveMapPayload) MutateMapId(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func LeaveMapPayloadStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func LeaveMapPayloadAddMapId(builder *flatbuffers.Builder, mapId uint32) {
	builder.PrependUint32Slot(0, mapId, 0)
}
func LeaveMapPayloadEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
type MovePayload struct {
	_tab flatbuffers.Table
}

func GetRootAsMovePayload(buf []byte, offset flatbuffers.UOffsetT) *MovePayload {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MovePayload{}
	x.Init(buf, n+offset)
	return x
}

func FinishMovePayloadBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMovePayload(buf []byte, offset flatbuffers.UOffsetT) *MovePayload {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MovePayload{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMovePayloadBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MovePayload) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MovePayload) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MovePayload) Vx() int16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MovePayload) MutateVx(n int16) bool {
	return rcv._tab.MutateInt16Slot(4, n)
}

func (rcv *MovePayload) Vy() int16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MovePayload) MutateVy(n int16) bool {
	return rcv._tab.MutateInt16Slot(6, n)
}

func MovePayloadStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func MovePayloadAddVx(builder *flatbuffers.Builder, vx int16) {
	builder.PrependInt16Slot(0, vx, 0)
}
func MovePayloadAddVy(builder *flatbuffers.Builder, vy int16) {
	builder.PrependInt16Slot(1, vy, 0)
}
func MovePayloadEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
type InteractPayload struct {
	_tab flatbuffers.Table
}

func GetRootAsInteractPayload(buf []byte, offset flatbuffers.UOffsetT) *InteractPayload {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &InteractPayload{}
	x.Init(buf, n+offset)
	return x
}

func FinishInteractPayloadBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsInteractPayload(buf []byte, offset flatbuffers.UOffsetT) *InteractPayload {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &InteractPayload{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedInteractPayloadBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *InteractPayload) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *InteractPayload) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *InteractPayload) TargetEntityId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *InteractPayload) MutateTargetEntityId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *InteractPayload) HasWorldPos() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *InteractPayload) MutateHasWorldPos(n bool) bool {
	return rcv._tab.MutateBoolSlot(6, n)
}

func (rcv *InteractPayload) WorldX() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *InteractPayload) MutateWorldX(n int32) bool {
	return rcv._tab.MutateInt32Slot(8, n)
}

func (rcv *InteractPayload) WorldY() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *InteractPayload) MutateWorldY(n int32) bool {
	return rcv._tab.MutateInt32Slot(10, n)
}

func InteractPayloadStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func InteractPayloadAddTargetEntityId(builder *flatbuffers.Builder, targetEntityId uint64) {
	builder.PrependUint64Slot(0, targetEntityId, 0)
}
func InteractPayloadAddHasWorldPos(builder *flatbuffers.Builder, hasWorldPos bool) {
	builder.PrependBoolSlot(1, hasWorldPos, false)
}
func InteractPayloadAddWorldX(builder *flatbuffers.Builder, worldX int32) {
	builder.PrependInt32Slot(2, worldX, 0)
}
func InteractPayloadAddWorldY(builder *flatbuffers.Builder, worldY int32) {
	builder.PrependInt32Slot(3, worldY, 0)
}
func InteractPayloadEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
type ActionPayload struct {
	_tab flatbuffers.Table
}

func GetRootAsActionPayload(buf []byte, offset flatbuffers.UOffsetT) *ActionPayload {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ActionPayload{}
	x.Init(buf, n+offset)
	return x
}

func FinishActionPayloadBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsActionPayload(buf []byte, offset flatbuffers.UOffsetT) *ActionPayload {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ActionPayload{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedActionPayloadBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ActionPayload) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ActionPayload) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ActionPayload) ActionId() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ActionPayload) MutateActionId(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func (rcv *ActionPayload) Data(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *ActionPayload) DataLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *ActionPayload) DataBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ActionPayload) MutateData(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func ActionPayloadStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func ActionPayloadAddActionId(builder *flatbuffers.Builder, actionId uint32) {
	builder.PrependUint32Slot(0, actionId, 0)
}
func ActionPayloadAddData(builder *flatbuffers.Builder, data flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(data), 0)
}
func ActionPayloadStartDataVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func ActionPayloadEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
type SpectatePayload struct {
	_tab flatbuffers.Table
}

func GetRootAsSpectatePayload(buf []byte, offset flatbuffers.UOffsetT) *SpectatePayload {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SpectatePayload{}
	x.Init(buf, n+offset)
	return x
}

func FinishSpectatePayloadBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsSpectatePayload(buf []byte, offset flatbuffers.UOffsetT) *SpectatePayload {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SpectatePayload{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedSpectatePayloadBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *SpectatePayload) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SpectatePayload) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SpectatePayload) MapId() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SpectatePayload) MutateMapId(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func (rcv *SpectatePayload) InstanceHint() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *SpectatePayload) Mode() SpectateMode {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return SpectateMode(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *SpectatePayload) MutateMode(n SpectateMode) bool {
	return rcv._tab.MutateByteSlot(8, byte(n))
}

func (rcv *SpectatePayload) TargetPlayerId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SpectatePayload) MutateTargetPlayerId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(10, n)
}

func SpectatePayloadStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func SpectatePayloadAddMapId(builder *flatbuffers.Builder, mapId uint32) {
	builder.PrependUint32Slot(0, mapId, 0)
}
func SpectatePayloadAddInstanceHint(builder *flatbuffers.Builder, instanceHint flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(instanceHint), 0)
}
func SpectatePayloadAddMode(builder *flatbuffers.Builder, mode SpectateMode) {
	builder.PrependByteSlot(2, byte(mode), 0)
}
func SpectatePayloadAddTargetPlayerId(builder *flatbuffers.Builder, targetPlayerId uint64) {
	builder.PrependUint64Slot(3, targetPlayerId, 0)
}
func SpectatePayloadEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
type DesignerCommandPayload struct {
	_tab flatbuffers.Table
}

func GetRootAsDesignerCommandPayload(buf []byte, offset flatbuffers.UOffsetT) *DesignerCommandPayload {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &DesignerCommandPayload{}
	x.Init(buf, n+offset)
	return x
}

func FinishDesignerCommandPayloadBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsDesignerCommandPayload(buf []byte, offset flatbuffers.UOffsetT) *DesignerCommandPayload {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &DesignerCommandPayload{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedDesignerCommandPayloadBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *DesignerCommandPayload) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *DesignerCommandPayload) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *DesignerCommandPayload) Opcode() DesignerOpcode {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return DesignerOpcode(rcv._tab.GetUint16(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *DesignerCommandPayload) MutateOpcode(n DesignerOpcode) bool {
	return rcv._tab.MutateUint16Slot(4, uint16(n))
}

func (rcv *DesignerCommandPayload) Data(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *DesignerCommandPayload) DataLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *DesignerCommandPayload) DataBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *DesignerCommandPayload) MutateData(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func DesignerCommandPayloadStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func DesignerCommandPayloadAddOpcode(builder *flatbuffers.Builder, opcode DesignerOpcode) {
	builder.PrependUint16Slot(0, uint16(opcode), 0)
}
func DesignerCommandPayloadAddData(builder *flatbuffers.Builder, data flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(data), 0)
}
func DesignerCommandPayloadStartDataVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func DesignerCommandPayloadEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
type TilePlacement struct {
	_tab flatbuffers.Table
}

func GetRootAsTilePlacement(buf []byte, offset flatbuffers.UOffsetT) *TilePlacement {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TilePlacement{}
	x.Init(buf, n+offset)
	return x
}

func FinishTilePlacementBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsTilePlacement(buf []byte, offset flatbuffers.UOffsetT) *TilePlacement {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &TilePlacement{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedTilePlacementBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *TilePlacement) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TilePlacement) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TilePlacement) LayerId() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *TilePlacement) MutateLayerId(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func (rcv *TilePlacement) X() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *TilePlacement) MutateX(n int32) bool {
	return rcv._tab.MutateInt32Slot(6, n)
}

func (rcv *TilePlacement) Y() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *TilePlacement) MutateY(n int32) bool {
	return rcv._tab.MutateInt32Slot(8, n)
}

func (rcv *TilePlacement) EntityTypeId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *TilePlacement) MutateEntityTypeId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(10, n)
}

func (rcv *TilePlacement) AnimOverride() int16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetInt16(o + rcv._tab.Pos)
	}
	return -1
}

func (rcv *TilePlacement) MutateAnimOverride(n int16) bool {
	return rcv._tab.MutateInt16Slot(12, n)
}

func (rcv *TilePlacement) CollisionShapeOverride() int16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetInt16(o + rcv._tab.Pos)
	}
	return -1
}

func (rcv *TilePlacement) MutateCollisionShapeOverride(n int16) bool {
	return rcv._tab.MutateInt16Slot(14, n)
}

func (rcv *TilePlacement) CollisionMaskOverride() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return -1
}

func (rcv *TilePlacement) MutateCollisionMaskOverride(n int64) bool {
	return rcv._tab.MutateInt64Slot(16, n)
}

func TilePlacementStart(builder *flatbuffers.Builder) {
	builder.StartObject(7)
}
func TilePlacementAddLayerId(builder *flatbuffers.Builder, layerId uint32) {
	builder.PrependUint32Slot(0, layerId, 0)
}
func TilePlacementAddX(builder *flatbuffers.Builder, x int32) {
	builder.PrependInt32Slot(1, x, 0)
}
func TilePlacementAddY(builder *flatbuffers.Builder, y int32) {
	builder.PrependInt32Slot(2, y, 0)
}
func TilePlacementAddEntityTypeId(builder *flatbuffers.Builder, entityTypeId uint64) {
	builder.PrependUint64Slot(3, entityTypeId, 0)
}
func TilePlacementAddAnimOverride(builder *flatbuffers.Builder, animOverride int16) {
	builder.PrependInt16Slot(4, animOverride, -1)
}
func TilePlacementAddCollisionShapeOverride(builder *flatbuffers.Builder, collisionShapeOverride int16) {
	builder.PrependInt16Slot(5, collisionShapeOverride, -1)
}
func TilePlacementAddCollisionMaskOverride(builder *flatbuffers.Builder, collisionMaskOverride int64) {
	builder.PrependInt64Slot(6, collisionMaskOverride, -1)
}
func TilePlacementEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
type PlaceTilesPayload struct {
	_tab flatbuffers.Table
}

func GetRootAsPlaceTilesPayload(buf []byte, offset flatbuffers.UOffsetT) *PlaceTilesPayload {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PlaceTilesPayload{}
	x.Init(buf, n+offset)
	return x
}

func FinishPlaceTilesPayloadBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsPlaceTilesPayload(buf []byte, offset flatbuffers.UOffsetT) *PlaceTilesPayload {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &PlaceTilesPayload{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedPlaceTilesPayloadBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *PlaceTilesPayload) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PlaceTilesPayload) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *PlaceTilesPayload) MapId() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *PlaceTilesPayload) MutateMapId(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func (rcv *PlaceTilesPayload) Tiles(obj *TilePlacement, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *PlaceTilesPayload) TilesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func PlaceTilesPayloadStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func PlaceTilesPayloadAddMapId(builder *flatbuffers.Builder, mapId uint32) {
	builder.PrependUint32Slot(0, mapId, 0)
}
func PlaceTilesPayloadAddTiles(builder *flatbuffers.Builder, tiles flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(tiles), 0)
}
func PlaceTilesPayloadStartTilesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func PlaceTilesPayloadEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
type EraseTilePoint struct {
	_tab flatbuffers.Table
}

func GetRootAsEraseTilePoint(buf []byte, offset flatbuffers.UOffsetT) *EraseTilePoint {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &EraseTilePoint{}
	x.Init(buf, n+offset)
	return x
}

func FinishEraseTilePointBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsEraseTilePoint(buf []byte, offset flatbuffers.UOffsetT) *EraseTilePoint {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &EraseTilePoint{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedEraseTilePointBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *EraseTilePoint) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *EraseTilePoint) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *EraseTilePoint) LayerId() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *EraseTilePoint) MutateLayerId(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func (rcv *EraseTilePoint) X() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *EraseTilePoint) MutateX(n int32) bool {
	return rcv._tab.MutateInt32Slot(6, n)
}

func (rcv *EraseTilePoint) Y() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *EraseTilePoint) MutateY(n int32) bool {
	return rcv._tab.MutateInt32Slot(8, n)
}

func EraseTilePointStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func EraseTilePointAddLayerId(builder *flatbuffers.Builder, layerId uint32) {
	builder.PrependUint32Slot(0, layerId, 0)
}
func EraseTilePointAddX(builder *flatbuffers.Builder, x int32) {
	builder.PrependInt32Slot(1, x, 0)
}
func EraseTilePointAddY(builder *flatbuffers.Builder, y int32) {
	builder.PrependInt32Slot(2, y, 0)
}
func EraseTilePointEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
type EraseTilesPayload struct {
	_tab flatbuffers.Table
}

func GetRootAsEraseTilesPayload(buf []byte, offset flatbuffers.UOffsetT) *EraseTilesPayload {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &EraseTilesPayload{}
	x.Init(buf, n+offset)
	return x
}

func FinishEraseTilesPayloadBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsEraseTilesPayload(buf []byte, offset flatbuffers.UOffsetT) *EraseTilesPayload {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &EraseTilesPayload{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedEraseTilesPayloadBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *EraseTilesPayload) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *EraseTilesPayload) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *EraseTilesPayload) MapId() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *EraseTilesPayload) MutateMapId(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func (rcv *EraseTilesPayload) Points(obj *EraseTilePoint, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *EraseTilesPayload) PointsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func EraseTilesPayloadStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func EraseTilesPayloadAddMapId(builder *flatbuffers.Builder, mapId uint32) {
	builder.PrependUint32Slot(0, mapId, 0)
}
func EraseTilesPayloadAddPoints(builder *flatbuffers.Builder, points flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(points), 0)
}
func EraseTilesPayloadStartPointsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func EraseTilesPayloadEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
type LightingCellPayload struct {
	_tab flatbuffers.Table
}

func GetRootAsLightingCellPayload(buf []byte, offset flatbuffers.UOffsetT) *LightingCellPayload {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &LightingCellPayload{}
	x.Init(buf, n+offset)
	return x
}

func FinishLightingCellPayloadBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsLightingCellPayload(buf []byte, offset flatbuffers.UOffsetT) *LightingCellPayload {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &LightingCellPayload{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedLightingCellPayloadBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *LightingCellPayload) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *LightingCellPayload) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *LightingCellPayload) LayerId() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *LightingCellPayload) MutateLayerId(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func (rcv *LightingCellPayload) X() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *LightingCellPayload) MutateX(n int32) bool {
	return rcv._tab.MutateInt32Slot(6, n)
}

func (rcv *LightingCellPayload) Y() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *LightingCellPayload) MutateY(n int32) bool {
	return rcv._tab.MutateInt32Slot(8, n)
}

func (rcv *LightingCellPayload) Color() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *LightingCellPayload) MutateColor(n uint32) bool {
	return rcv._tab.MutateUint32Slot(10, n)
}

func (rcv *LightingCellPayload) Intensity() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *LightingCellPayload) MutateIntensity(n byte) bool {
	return rcv._tab.MutateByteSlot(12, n)
}

func LightingCellPayloadStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func LightingCellPayloadAddLayerId(builder *flatbuffers.Builder, layerId uint32) {
	builder.PrependUint32Slot(0, layerId, 0)
}
func LightingCellPayloadAddX(builder *flatbuffers.Builder, x int32) {
	builder.PrependInt32Slot(1, x, 0)
}
func LightingCellPayloadAddY(builder *flatbuffers.Builder, y int32) {
	builder.PrependInt32Slot(2, y, 0)
}
func LightingCellPayloadAddColor(builder *flatbuffers.Builder, color uint32) {
	builder.PrependUint32Slot(3, color, 0)
}
func LightingCellPayloadAddIntensity(builder *flatbuffers.Builder, intensity byte) {
	builder.PrependByteSlot(4, intensity, 0)
}
func LightingCellPayloadEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
type PlaceLightingPayload struct {
	_tab flatbuffers.Table
}

func GetRootAsPlaceLightingPayload(buf []byte, offset flatbuffers.UOffsetT) *PlaceLightingPayload {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PlaceLightingPayload{}
	x.Init(buf, n+offset)
	return x
}

func FinishPlaceLightingPayloadBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsPlaceLightingPayload(buf []byte, offset flatbuffers.UOffsetT) *PlaceLightingPayload {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &PlaceLightingPayload{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedPlaceLightingPayloadBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *PlaceLightingPayload) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PlaceLightingPayload) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *PlaceLightingPayload) MapId() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *PlaceLightingPayload) MutateMapId(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func (rcv *PlaceLightingPayload) Cells(obj *LightingCellPayload, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *PlaceLightingPayload) CellsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func PlaceLightingPayloadStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func PlaceLightingPayloadAddMapId(builder *flatbuffers.Builder, mapId uint32) {
	builder.PrependUint32Slot(0, mapId, 0)
}
func PlaceLightingPayloadAddCells(builder *flatbuffers.Builder, cells flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(cells), 0)
}
func PlaceLightingPayloadStartCellsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func PlaceLightingPayloadEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
type HeartbeatPayload struct {
	_tab flatbuffers.Table
}

func GetRootAsHeartbeatPayload(buf []byte, offset flatbuffers.UOffsetT) *HeartbeatPayload {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &HeartbeatPayload{}
	x.Init(buf, n+offset)
	return x
}

func FinishHeartbeatPayloadBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsHeartbeatPayload(buf []byte, offset flatbuffers.UOffsetT) *HeartbeatPayload {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &HeartbeatPayload{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedHeartbeatPayloadBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *HeartbeatPayload) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *HeartbeatPayload) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *HeartbeatPayload) ClientNowMs() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *HeartbeatPayload) MutateClientNowMs(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func HeartbeatPayloadStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func HeartbeatPayloadAddClientNowMs(builder *flatbuffers.Builder, clientNowMs uint64) {
	builder.PrependUint64Slot(0, clientNowMs, 0)
}
func HeartbeatPayloadEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
type AckTickPayload struct {
	_tab flatbuffers.Table
}

func GetRootAsAckTickPayload(buf []byte, offset flatbuffers.UOffsetT) *AckTickPayload {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &AckTickPayload{}
	x.Init(buf, n+offset)
	return x
}

func FinishAckTickPayloadBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsAckTickPayload(buf []byte, offset flatbuffers.UOffsetT) *AckTickPayload {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &AckTickPayload{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedAckTickPayloadBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *AckTickPayload) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *AckTickPayload) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *AckTickPayload) LastAppliedTick() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AckTickPayload) MutateLastAppliedTick(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func AckTickPayloadStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func AckTickPayloadAddLastAppliedTick(builder *flatbuffers.Builder, lastAppliedTick uint64) {
	builder.PrependUint64Slot(0, lastAppliedTick, 0)
}
func AckTickPayloadEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
