package wfc

import "fmt"

// ChunkedOptions controls a multi-chunk generation pass. A "chunk" here
// is one WFC region; chunked generation tiles them left-to-right, top-to-
// bottom, feeding each chunk's right/bottom edge tiles forward as anchors
// for the next chunk's left/top edge.
//
// This is the procedural-Mapmaker workhorse: a 256x256 map is 16 chunks
// at 64x64 each, generated independently but seam-consistent. WFC's
// O(N^2) propagation cost stays bounded per chunk while the overall map
// grows arbitrarily large.
type ChunkedOptions struct {
	// ChunkW, ChunkH are the dimensions of each individual WFC region.
	// Total output size is (CountX * ChunkW) by (CountY * ChunkH).
	ChunkW, ChunkH int32

	// CountX, CountY are how many chunks to lay out on each axis.
	CountX, CountY int32

	// Seed is the master seed. Per-chunk seeds are derived deterministically
	// so the same master seed produces the same full output.
	Seed uint64

	// Anchors are designer-painted cells in WORLD coordinates (not chunk-
	// local). They get distributed to whichever chunk owns their cell.
	Anchors Anchors

	// BacktrackBudget and MaxReseeds are forwarded to each per-chunk
	// Generate call. 0 = use package defaults.
	BacktrackBudget int
	MaxReseeds      int

	// BiomeCount enables the coarse biome pre-pass. When > 1 the
	// engine assigns each chunk a biome label via value noise (see
	// biome.go) and filters that chunk's tileset through BiomePalette.
	// 0 / 1 disables biome filtering entirely; the engine behaves
	// identically to before.
	BiomeCount int

	// BiomeFrequency controls the smoothness of biome regions. 0 = use
	// package default. See BiomeMapOptions.Frequency.
	BiomeFrequency float64

	// BiomePalette returns the entity types allowed in biome `b`. The
	// engine never calls this with b outside [0, BiomeCount). Returning
	// nil or an empty slice means "use the full tileset for this
	// biome" (graceful degradation when an under-authored biome would
	// otherwise produce zero tiles).
	BiomePalette func(b int) []EntityTypeID

	// Constraints are forwarded to each per-chunk Generate call. They
	// apply at chunk-local coordinates (NOT world coordinates). For
	// world-wide constraints like "the entire map's borders are water",
	// the caller is responsible for translating into per-chunk anchors
	// or per-chunk constraints (a future helper might automate this).
	Constraints []Constraint
}

// GenerateChunked tiles WFC across (CountX * CountY) chunks, returning
// one Region containing the full result in world coordinates.
//
// Seam consistency is enforced by extracting each chunk's right column
// and bottom row after generation, then feeding those cells as anchors
// to the chunk(s) immediately to the east and south. The west and north
// neighbors will already have been generated by the time we visit a
// chunk because we walk left-to-right, top-to-bottom.
func GenerateChunked(ts *TileSet, opts ChunkedOptions) (*Region, error) {
	if ts == nil || ts.Len() == 0 {
		return nil, ErrEmptyTileSet
	}
	if opts.ChunkW <= 0 || opts.ChunkH <= 0 || opts.CountX <= 0 || opts.CountY <= 0 {
		return nil, ErrInvalidRegion
	}

	totalW := opts.CountX * opts.ChunkW
	totalH := opts.CountY * opts.ChunkH
	out := &Region{
		Width:  totalW,
		Height: totalH,
		Cells:  make([]Cell, 0, int(totalW)*int(totalH)),
	}

	// Pre-bucket designer anchors by (chunkX, chunkY) -> chunk-local cells.
	// Using a key of (cy * countX + cx) since both are int32 and small.
	type chunkKey struct{ cx, cy int32 }
	bucketed := make(map[chunkKey][]Cell, int(opts.CountX*opts.CountY))
	for _, a := range opts.Anchors.Cells {
		if a.X < 0 || a.Y < 0 || a.X >= totalW || a.Y >= totalH {
			continue
		}
		cx := a.X / opts.ChunkW
		cy := a.Y / opts.ChunkH
		bucketed[chunkKey{cx, cy}] = append(bucketed[chunkKey{cx, cy}], Cell{
			X:          a.X % opts.ChunkW,
			Y:          a.Y % opts.ChunkH,
			EntityType: a.EntityType,
		})
	}

	// Resolved chunks, in row-major order, indexed [cy][cx]. We need to keep
	// the previous row resolved so we can feed bottom-edge constraints to
	// the chunks below; each row drops out of memory once the row beneath
	// has consumed it. For now we keep them all to make the row-wise output
	// assembly straightforward.
	resolved := make([][]*Region, opts.CountY)
	for i := range resolved {
		resolved[i] = make([]*Region, opts.CountX)
	}

	// Optional biome pre-pass. Built once, consulted per-chunk to
	// filter the tileset down to biome-tagged tiles. Cheap (one
	// value-noise sample per chunk) so we always run it when enabled
	// rather than memoising.
	var biomeMap *BiomeMap
	useBiomes := opts.BiomeCount > 1 && opts.BiomePalette != nil
	if useBiomes {
		biomeMap = GenerateBiomeMap(BiomeMapOptions{
			CountX:     opts.CountX,
			CountY:     opts.CountY,
			BiomeCount: opts.BiomeCount,
			Seed:       opts.Seed,
			Frequency:  opts.BiomeFrequency,
		})
	}

	for cy := int32(0); cy < opts.CountY; cy++ {
		for cx := int32(0); cx < opts.CountX; cx++ {
			anchors := Anchors{Cells: append([]Cell(nil), bucketed[chunkKey{cx, cy}]...)}

			// Seam from west neighbor: feed neighbor's east-edge cells as
			// chunk-local west-edge anchors (x=0). Per-chunk Region.Cells
			// is row-major (tryGenerate guarantees this), so direct
			// indexing avoids an O(N) scan inside Region.At.
			if cx > 0 {
				west := resolved[cy][cx-1]
				for y := int32(0); y < opts.ChunkH; y++ {
					et := west.Cells[y*opts.ChunkW+(opts.ChunkW-1)].EntityType
					anchors.Cells = append(anchors.Cells, Cell{X: 0, Y: y, EntityType: et})
				}
			}
			// Seam from north neighbor: feed neighbor's south-edge cells as
			// chunk-local north-edge anchors (y=0).
			if cy > 0 {
				north := resolved[cy-1][cx]
				for x := int32(0); x < opts.ChunkW; x++ {
					et := north.Cells[(opts.ChunkH-1)*opts.ChunkW+x].EntityType
					anchors.Cells = append(anchors.Cells, Cell{X: x, Y: 0, EntityType: et})
				}
			}

			// Derive a deterministic per-chunk seed from the master seed and
			// chunk coordinates. Two splitmix64 mixes keep the per-chunk
			// streams well-separated even for adjacent chunks.
			chunkSeed := splitMix64(opts.Seed +
				uint64(cy)*0x9E3779B97F4A7C15 +
				uint64(cx)*0xC6BC279692B5C323)

			// Per-chunk tileset: full tileset by default, biome-filtered
			// when the biome pre-pass is enabled. FilterTilesByBiome
			// returns the original tileset on empty filter (so under-
			// authored biomes degrade to "any tile" rather than failing).
			chunkTS := ts
			if useBiomes {
				biome := biomeMap.At(cx, cy)
				if biome >= 0 {
					chunkTS = FilterTilesByBiome(ts, opts.BiomePalette(biome))
				}
			}

			region, err := Generate(chunkTS, GenerateOptions{
				Width:           opts.ChunkW,
				Height:          opts.ChunkH,
				Seed:            chunkSeed,
				Anchors:         anchors,
				BacktrackBudget: opts.BacktrackBudget,
				MaxReseeds:      opts.MaxReseeds,
				Constraints:     opts.Constraints,
			})
			if err != nil {
				return nil, fmt.Errorf("wfc: chunk (%d,%d): %w", cx, cy, err)
			}
			resolved[cy][cx] = region
		}
	}

	// Assemble the full region in world coordinates.
	for cy := int32(0); cy < opts.CountY; cy++ {
		for y := int32(0); y < opts.ChunkH; y++ {
			for cx := int32(0); cx < opts.CountX; cx++ {
				chunk := resolved[cy][cx]
				for x := int32(0); x < opts.ChunkW; x++ {
					c := chunk.Cells[y*opts.ChunkW+x]
					out.Cells = append(out.Cells, Cell{
						X:          cx*opts.ChunkW + x,
						Y:          cy*opts.ChunkH + y,
						EntityType: c.EntityType,
					})
				}
			}
		}
	}
	return out, nil
}
