// Boxland — OAuth providers for player accounts.
//
// PLAN.md §4c: Google, Apple, Discord — each behind a feature flag.
// Endpoints under /auth/oauth/* so iOS reuses them at v1.1.
//
// One Provider interface, registered into a Registry at boot. Feature
// flags live in cmd/boxland/main.go; this package only knows about
// "registered providers" + the standard Authorization-Code-with-PKCE
// flow.

package player

import (
	"context"
	"crypto/rand"
	"encoding/base64"
	"errors"
	"fmt"
	"net/http"
	"sync"
	"time"

	"github.com/jackc/pgx/v5"
)

// Provider is implemented by Google, Apple, Discord, etc. The interface
// is intentionally narrow: each provider knows how to hand the runtime a
// (provider_user_id, email) pair given a callback request, and that's
// the only data we persist.
type Provider interface {
	// Name is the stable id stored in player_oauth_links.provider.
	Name() string

	// AuthCodeURL returns the URL the browser should redirect to.
	// `state` and `pkceVerifier` are generated by the gateway and stored
	// in a short-lived cookie; the provider weaves them into the URL.
	AuthCodeURL(state, pkceVerifier string) string

	// Exchange consumes the authorization code on callback and returns
	// the (provider_user_id, email) pair needed to look up or create
	// the player_oauth_links row. PKCE verifier is the same one
	// AuthCodeURL was given.
	Exchange(ctx context.Context, code, pkceVerifier string) (providerUserID, email string, err error)
}

// Registry maps provider names to their implementations.
type Registry struct {
	mu        sync.RWMutex
	providers map[string]Provider
}

// NewRegistry returns an empty registry.
func NewRegistry() *Registry {
	return &Registry{providers: make(map[string]Provider)}
}

// Register adds a provider. Panics on duplicate names so misconfigurations
// surface at boot.
func (r *Registry) Register(p Provider) {
	r.mu.Lock()
	defer r.mu.Unlock()
	if _, ok := r.providers[p.Name()]; ok {
		panic(fmt.Sprintf("oauth: duplicate provider %q", p.Name()))
	}
	r.providers[p.Name()] = p
}

// Get returns the provider by name.
func (r *Registry) Get(name string) (Provider, bool) {
	r.mu.RLock()
	defer r.mu.RUnlock()
	p, ok := r.providers[name]
	return p, ok
}

// Names returns every registered provider name. Used by the login UI to
// render only the buttons that are actually wired.
func (r *Registry) Names() []string {
	r.mu.RLock()
	defer r.mu.RUnlock()
	out := make([]string, 0, len(r.providers))
	for n := range r.providers {
		out = append(out, n)
	}
	return out
}

// ---- Service-side OAuth helpers ----

// LinkOrCreatePlayer is the per-callback path: given the (provider, ID,
// email) tuple from the IdP, either look up the linked player and return
// it, or create a brand-new player + link in one transaction.
//
// The created player is marked email_verified=true if the email was
// confirmed by the IdP (Google + Apple do; Discord doesn't for some
// account types). Caller passes `emailVerified=true` only when sure.
func (s *Service) LinkOrCreatePlayer(
	ctx context.Context,
	provider, providerUserID, email string,
	emailVerified bool,
) (*Player, error) {
	if providerUserID == "" {
		return nil, errors.New("oauth: provider_user_id required")
	}

	// Existing link?
	var playerID int64
	err := s.Pool.QueryRow(ctx,
		`SELECT player_id FROM player_oauth_links WHERE provider = $1 AND provider_user_id = $2`,
		provider, providerUserID,
	).Scan(&playerID)
	if err == nil {
		return s.FindByID(ctx, playerID)
	}

	// Existing player by email? Link the OAuth account to it.
	if email != "" {
		if existing, err := s.FindByEmail(ctx, email); err == nil {
			if _, err := s.Pool.Exec(ctx,
				`INSERT INTO player_oauth_links (player_id, provider, provider_user_id) VALUES ($1, $2, $3)`,
				existing.ID, provider, providerUserID,
			); err != nil {
				return nil, fmt.Errorf("link existing player: %w", err)
			}
			if emailVerified && !existing.EmailVerified {
				if _, err := s.Pool.Exec(ctx,
					`UPDATE players SET email_verified = true, updated_at = now() WHERE id = $1`,
					existing.ID,
				); err != nil {
					return nil, fmt.Errorf("mark verified: %w", err)
				}
				existing.EmailVerified = true
			}
			return existing, nil
		}
	}

	// Brand-new player.
	tx, err := s.Pool.BeginTx(ctx, pgx.TxOptions{})
	if err != nil {
		return nil, fmt.Errorf("begin tx: %w", err)
	}
	defer func() { _ = tx.Rollback(ctx) }()

	row := tx.QueryRow(ctx, `
		INSERT INTO players (email, password_hash, email_verified)
		VALUES ($1, NULL, $2)
		RETURNING id, email, password_hash, email_verified, display_name, created_at, updated_at
	`, email, emailVerified)
	p, err := scanPlayer(row)
	if err != nil {
		return nil, fmt.Errorf("create oauth player: %w", err)
	}

	if _, err := tx.Exec(ctx,
		`INSERT INTO player_oauth_links (player_id, provider, provider_user_id) VALUES ($1, $2, $3)`,
		p.ID, provider, providerUserID,
	); err != nil {
		return nil, fmt.Errorf("link oauth: %w", err)
	}
	if err := tx.Commit(ctx); err != nil {
		return nil, fmt.Errorf("commit: %w", err)
	}
	return p, nil
}

// ---- State + PKCE ----

// NewOAuthState mints a random state token suitable for the OAuth flow.
// 32 bytes of entropy, base64-url encoded.
func NewOAuthState() (string, error) {
	buf := make([]byte, 32)
	if _, err := rand.Read(buf); err != nil {
		return "", err
	}
	return base64.RawURLEncoding.EncodeToString(buf), nil
}

// NewPKCEVerifier mints a code verifier per RFC 7636. We use the maximum
// 128-character length; the corresponding S256 challenge is computed by
// the provider implementation.
func NewPKCEVerifier() (string, error) {
	buf := make([]byte, 96) // 96 raw bytes = 128 chars when base64url-encoded
	if _, err := rand.Read(buf); err != nil {
		return "", err
	}
	return base64.RawURLEncoding.EncodeToString(buf), nil
}

// ---- HTTP cookie helpers ----

// OAuthStateCookie is the short-lived cookie holding (state || verifier)
// during the OAuth round trip. JSON-encoded so the format can grow.
const OAuthStateCookie = "boxland_oauth_state"

// OAuthStateCookieTTL bounds the round-trip duration. Real-world flows
// finish in <30s; we allow a generous 10 minutes for slow IdP redirects.
const OAuthStateCookieTTL = 10 * time.Minute

// SetOAuthStateCookie sets the round-trip cookie. The value is the raw
// concatenation `state + ":" + verifier` so we don't need a JSON parse
// on the callback path (which has no body).
func SetOAuthStateCookie(w http.ResponseWriter, secure bool, state, verifier string) {
	http.SetCookie(w, &http.Cookie{
		Name:     OAuthStateCookie,
		Value:    state + ":" + verifier,
		Path:     "/auth/oauth",
		MaxAge:   int(OAuthStateCookieTTL.Seconds()),
		HttpOnly: true,
		Secure:   secure,
		SameSite: http.SameSiteLaxMode, // Lax so the IdP redirect carries it back
	})
}

// ClearOAuthStateCookie blanks the round-trip cookie; the gateway calls
// this on both success and failure paths.
func ClearOAuthStateCookie(w http.ResponseWriter, secure bool) {
	http.SetCookie(w, &http.Cookie{
		Name: OAuthStateCookie, Value: "", Path: "/auth/oauth",
		MaxAge: -1, HttpOnly: true, Secure: secure, SameSite: http.SameSiteLaxMode,
	})
}
