// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { ArtifactKind } from '../../boxland/proto/artifact-kind.js';
import { DiffOp } from '../../boxland/proto/diff-op.js';


export class ArtifactDiff {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ArtifactDiff {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsArtifactDiff(bb:flatbuffers.ByteBuffer, obj?:ArtifactDiff):ArtifactDiff {
  return (obj || new ArtifactDiff()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsArtifactDiff(bb:flatbuffers.ByteBuffer, obj?:ArtifactDiff):ArtifactDiff {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ArtifactDiff()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

kind():ArtifactKind {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : ArtifactKind.Asset;
}

artifactId():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

op():DiffOp {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : DiffOp.Created;
}

summaryLine():string|null
summaryLine(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
summaryLine(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

structuredDiff(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
}

structuredDiffLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

structuredDiffArray():Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

static startArtifactDiff(builder:flatbuffers.Builder) {
  builder.startObject(5);
}

static addKind(builder:flatbuffers.Builder, kind:ArtifactKind) {
  builder.addFieldInt8(0, kind, ArtifactKind.Asset);
}

static addArtifactId(builder:flatbuffers.Builder, artifactId:bigint) {
  builder.addFieldInt64(1, artifactId, BigInt('0'));
}

static addOp(builder:flatbuffers.Builder, op:DiffOp) {
  builder.addFieldInt8(2, op, DiffOp.Created);
}

static addSummaryLine(builder:flatbuffers.Builder, summaryLineOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, summaryLineOffset, 0);
}

static addStructuredDiff(builder:flatbuffers.Builder, structuredDiffOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, structuredDiffOffset, 0);
}

static createStructuredDiffVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startStructuredDiffVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static endArtifactDiff(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createArtifactDiff(builder:flatbuffers.Builder, kind:ArtifactKind, artifactId:bigint, op:DiffOp, summaryLineOffset:flatbuffers.Offset, structuredDiffOffset:flatbuffers.Offset):flatbuffers.Offset {
  ArtifactDiff.startArtifactDiff(builder);
  ArtifactDiff.addKind(builder, kind);
  ArtifactDiff.addArtifactId(builder, artifactId);
  ArtifactDiff.addOp(builder, op);
  ArtifactDiff.addSummaryLine(builder, summaryLineOffset);
  ArtifactDiff.addStructuredDiff(builder, structuredDiffOffset);
  return ArtifactDiff.endArtifactDiff(builder);
}
}
