// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class AudioEvent {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):AudioEvent {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsAudioEvent(bb:flatbuffers.ByteBuffer, obj?:AudioEvent):AudioEvent {
  return (obj || new AudioEvent()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsAudioEvent(bb:flatbuffers.ByteBuffer, obj?:AudioEvent):AudioEvent {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new AudioEvent()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

soundId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

hasPosition():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

x():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

y():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

volume():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 255;
}

pitch():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readInt16(this.bb_pos + offset) : 0;
}

static startAudioEvent(builder:flatbuffers.Builder) {
  builder.startObject(6);
}

static addSoundId(builder:flatbuffers.Builder, soundId:number) {
  builder.addFieldInt32(0, soundId, 0);
}

static addHasPosition(builder:flatbuffers.Builder, hasPosition:boolean) {
  builder.addFieldInt8(1, +hasPosition, +false);
}

static addX(builder:flatbuffers.Builder, x:number) {
  builder.addFieldInt32(2, x, 0);
}

static addY(builder:flatbuffers.Builder, y:number) {
  builder.addFieldInt32(3, y, 0);
}

static addVolume(builder:flatbuffers.Builder, volume:number) {
  builder.addFieldInt8(4, volume, 255);
}

static addPitch(builder:flatbuffers.Builder, pitch:number) {
  builder.addFieldInt16(5, pitch, 0);
}

static endAudioEvent(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createAudioEvent(builder:flatbuffers.Builder, soundId:number, hasPosition:boolean, x:number, y:number, volume:number, pitch:number):flatbuffers.Offset {
  AudioEvent.startAudioEvent(builder);
  AudioEvent.addSoundId(builder, soundId);
  AudioEvent.addHasPosition(builder, hasPosition);
  AudioEvent.addX(builder, x);
  AudioEvent.addY(builder, y);
  AudioEvent.addVolume(builder, volume);
  AudioEvent.addPitch(builder, pitch);
  return AudioEvent.endAudioEvent(builder);
}
}
