// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { EditorMapLayer } from '../../boxland/proto/editor-map-layer.js';
import { EditorMapTile } from '../../boxland/proto/editor-map-tile.js';


export class EditorMapmakerBody {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):EditorMapmakerBody {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsEditorMapmakerBody(bb:flatbuffers.ByteBuffer, obj?:EditorMapmakerBody):EditorMapmakerBody {
  return (obj || new EditorMapmakerBody()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsEditorMapmakerBody(bb:flatbuffers.ByteBuffer, obj?:EditorMapmakerBody):EditorMapmakerBody {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new EditorMapmakerBody()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

mapId():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

mapName():string|null
mapName(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
mapName(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

width():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

height():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

layers(index: number, obj?:EditorMapLayer):EditorMapLayer|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? (obj || new EditorMapLayer()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

layersLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

tiles(index: number, obj?:EditorMapTile):EditorMapTile|null {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? (obj || new EditorMapTile()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

tilesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

locks(index: number, obj?:EditorMapTile):EditorMapTile|null {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? (obj || new EditorMapTile()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

locksLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startEditorMapmakerBody(builder:flatbuffers.Builder) {
  builder.startObject(7);
}

static addMapId(builder:flatbuffers.Builder, mapId:bigint) {
  builder.addFieldInt64(0, mapId, BigInt('0'));
}

static addMapName(builder:flatbuffers.Builder, mapNameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, mapNameOffset, 0);
}

static addWidth(builder:flatbuffers.Builder, width:number) {
  builder.addFieldInt32(2, width, 0);
}

static addHeight(builder:flatbuffers.Builder, height:number) {
  builder.addFieldInt32(3, height, 0);
}

static addLayers(builder:flatbuffers.Builder, layersOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, layersOffset, 0);
}

static createLayersVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startLayersVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addTiles(builder:flatbuffers.Builder, tilesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(5, tilesOffset, 0);
}

static createTilesVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startTilesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addLocks(builder:flatbuffers.Builder, locksOffset:flatbuffers.Offset) {
  builder.addFieldOffset(6, locksOffset, 0);
}

static createLocksVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startLocksVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endEditorMapmakerBody(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createEditorMapmakerBody(builder:flatbuffers.Builder, mapId:bigint, mapNameOffset:flatbuffers.Offset, width:number, height:number, layersOffset:flatbuffers.Offset, tilesOffset:flatbuffers.Offset, locksOffset:flatbuffers.Offset):flatbuffers.Offset {
  EditorMapmakerBody.startEditorMapmakerBody(builder);
  EditorMapmakerBody.addMapId(builder, mapId);
  EditorMapmakerBody.addMapName(builder, mapNameOffset);
  EditorMapmakerBody.addWidth(builder, width);
  EditorMapmakerBody.addHeight(builder, height);
  EditorMapmakerBody.addLayers(builder, layersOffset);
  EditorMapmakerBody.addTiles(builder, tilesOffset);
  EditorMapmakerBody.addLocks(builder, locksOffset);
  return EditorMapmakerBody.endEditorMapmakerBody(builder);
}
}
