// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class JoinMapPayload {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):JoinMapPayload {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsJoinMapPayload(bb:flatbuffers.ByteBuffer, obj?:JoinMapPayload):JoinMapPayload {
  return (obj || new JoinMapPayload()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsJoinMapPayload(bb:flatbuffers.ByteBuffer, obj?:JoinMapPayload):JoinMapPayload {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new JoinMapPayload()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

mapId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

instanceHint():string|null
instanceHint(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
instanceHint(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startJoinMapPayload(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addMapId(builder:flatbuffers.Builder, mapId:number) {
  builder.addFieldInt32(0, mapId, 0);
}

static addInstanceHint(builder:flatbuffers.Builder, instanceHintOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, instanceHintOffset, 0);
}

static endJoinMapPayload(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createJoinMapPayload(builder:flatbuffers.Builder, mapId:number, instanceHintOffset:flatbuffers.Offset):flatbuffers.Offset {
  JoinMapPayload.startJoinMapPayload(builder);
  JoinMapPayload.addMapId(builder, mapId);
  JoinMapPayload.addInstanceHint(builder, instanceHintOffset);
  return JoinMapPayload.endJoinMapPayload(builder);
}
}
