// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { MutationKind } from '../../boxland/proto/mutation-kind.js';
import { ProtocolVersion } from '../../boxland/proto/protocol-version.js';


export class Mutation {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Mutation {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsMutation(bb:flatbuffers.ByteBuffer, obj?:Mutation):Mutation {
  return (obj || new Mutation()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsMutation(bb:flatbuffers.ByteBuffer, obj?:Mutation):Mutation {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Mutation()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

protocolVersion(obj?:ProtocolVersion):ProtocolVersion|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new ProtocolVersion()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

tick():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

seq():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

kind():MutationKind {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : MutationKind.EntitySpawn;
}

entityId():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

typeId():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

x():number {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

y():number {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

auxU32():number {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

auxU32B():number {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

payload(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 24);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
}

payloadLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 24);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

payloadArray():Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 24);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

static startMutation(builder:flatbuffers.Builder) {
  builder.startObject(11);
}

static addProtocolVersion(builder:flatbuffers.Builder, protocolVersionOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, protocolVersionOffset, 0);
}

static addTick(builder:flatbuffers.Builder, tick:bigint) {
  builder.addFieldInt64(1, tick, BigInt('0'));
}

static addSeq(builder:flatbuffers.Builder, seq:number) {
  builder.addFieldInt32(2, seq, 0);
}

static addKind(builder:flatbuffers.Builder, kind:MutationKind) {
  builder.addFieldInt8(3, kind, MutationKind.EntitySpawn);
}

static addEntityId(builder:flatbuffers.Builder, entityId:bigint) {
  builder.addFieldInt64(4, entityId, BigInt('0'));
}

static addTypeId(builder:flatbuffers.Builder, typeId:number) {
  builder.addFieldInt32(5, typeId, 0);
}

static addX(builder:flatbuffers.Builder, x:number) {
  builder.addFieldInt32(6, x, 0);
}

static addY(builder:flatbuffers.Builder, y:number) {
  builder.addFieldInt32(7, y, 0);
}

static addAuxU32(builder:flatbuffers.Builder, auxU32:number) {
  builder.addFieldInt32(8, auxU32, 0);
}

static addAuxU32B(builder:flatbuffers.Builder, auxU32B:number) {
  builder.addFieldInt32(9, auxU32B, 0);
}

static addPayload(builder:flatbuffers.Builder, payloadOffset:flatbuffers.Offset) {
  builder.addFieldOffset(10, payloadOffset, 0);
}

static createPayloadVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startPayloadVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static endMutation(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // protocol_version
  return offset;
}

static createMutation(builder:flatbuffers.Builder, protocolVersionOffset:flatbuffers.Offset, tick:bigint, seq:number, kind:MutationKind, entityId:bigint, typeId:number, x:number, y:number, auxU32:number, auxU32B:number, payloadOffset:flatbuffers.Offset):flatbuffers.Offset {
  Mutation.startMutation(builder);
  Mutation.addProtocolVersion(builder, protocolVersionOffset);
  Mutation.addTick(builder, tick);
  Mutation.addSeq(builder, seq);
  Mutation.addKind(builder, kind);
  Mutation.addEntityId(builder, entityId);
  Mutation.addTypeId(builder, typeId);
  Mutation.addX(builder, x);
  Mutation.addY(builder, y);
  Mutation.addAuxU32(builder, auxU32);
  Mutation.addAuxU32B(builder, auxU32B);
  Mutation.addPayload(builder, payloadOffset);
  return Mutation.endMutation(builder);
}
}
