// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class RemoveLevelEntityPayload {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):RemoveLevelEntityPayload {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsRemoveLevelEntityPayload(bb:flatbuffers.ByteBuffer, obj?:RemoveLevelEntityPayload):RemoveLevelEntityPayload {
  return (obj || new RemoveLevelEntityPayload()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsRemoveLevelEntityPayload(bb:flatbuffers.ByteBuffer, obj?:RemoveLevelEntityPayload):RemoveLevelEntityPayload {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new RemoveLevelEntityPayload()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

levelId():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

placementId():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

static startRemoveLevelEntityPayload(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addLevelId(builder:flatbuffers.Builder, levelId:bigint) {
  builder.addFieldInt64(0, levelId, BigInt('0'));
}

static addPlacementId(builder:flatbuffers.Builder, placementId:bigint) {
  builder.addFieldInt64(1, placementId, BigInt('0'));
}

static endRemoveLevelEntityPayload(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createRemoveLevelEntityPayload(builder:flatbuffers.Builder, levelId:bigint, placementId:bigint):flatbuffers.Offset {
  RemoveLevelEntityPayload.startRemoveLevelEntityPayload(builder);
  RemoveLevelEntityPayload.addLevelId(builder, levelId);
  RemoveLevelEntityPayload.addPlacementId(builder, placementId);
  return RemoveLevelEntityPayload.endRemoveLevelEntityPayload(builder);
}
}
