// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class SetTileRotationPayload {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):SetTileRotationPayload {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSetTileRotationPayload(bb:flatbuffers.ByteBuffer, obj?:SetTileRotationPayload):SetTileRotationPayload {
  return (obj || new SetTileRotationPayload()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSetTileRotationPayload(bb:flatbuffers.ByteBuffer, obj?:SetTileRotationPayload):SetTileRotationPayload {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SetTileRotationPayload()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

mapId():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

layerId():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

x():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

y():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

rotationDegrees():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readInt16(this.bb_pos + offset) : 0;
}

static startSetTileRotationPayload(builder:flatbuffers.Builder) {
  builder.startObject(5);
}

static addMapId(builder:flatbuffers.Builder, mapId:bigint) {
  builder.addFieldInt64(0, mapId, BigInt('0'));
}

static addLayerId(builder:flatbuffers.Builder, layerId:number) {
  builder.addFieldInt32(1, layerId, 0);
}

static addX(builder:flatbuffers.Builder, x:number) {
  builder.addFieldInt32(2, x, 0);
}

static addY(builder:flatbuffers.Builder, y:number) {
  builder.addFieldInt32(3, y, 0);
}

static addRotationDegrees(builder:flatbuffers.Builder, rotationDegrees:number) {
  builder.addFieldInt16(4, rotationDegrees, 0);
}

static endSetTileRotationPayload(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createSetTileRotationPayload(builder:flatbuffers.Builder, mapId:bigint, layerId:number, x:number, y:number, rotationDegrees:number):flatbuffers.Offset {
  SetTileRotationPayload.startSetTileRotationPayload(builder);
  SetTileRotationPayload.addMapId(builder, mapId);
  SetTileRotationPayload.addLayerId(builder, layerId);
  SetTileRotationPayload.addX(builder, x);
  SetTileRotationPayload.addY(builder, y);
  SetTileRotationPayload.addRotationDegrees(builder, rotationDegrees);
  return SetTileRotationPayload.endSetTileRotationPayload(builder);
}
}
