// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class SetLevelEntityOverridesPayload {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):SetLevelEntityOverridesPayload {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSetLevelEntityOverridesPayload(bb:flatbuffers.ByteBuffer, obj?:SetLevelEntityOverridesPayload):SetLevelEntityOverridesPayload {
  return (obj || new SetLevelEntityOverridesPayload()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSetLevelEntityOverridesPayload(bb:flatbuffers.ByteBuffer, obj?:SetLevelEntityOverridesPayload):SetLevelEntityOverridesPayload {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SetLevelEntityOverridesPayload()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

levelId():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

placementId():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

instanceOverridesJson():string|null
instanceOverridesJson(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
instanceOverridesJson(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startSetLevelEntityOverridesPayload(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addLevelId(builder:flatbuffers.Builder, levelId:bigint) {
  builder.addFieldInt64(0, levelId, BigInt('0'));
}

static addPlacementId(builder:flatbuffers.Builder, placementId:bigint) {
  builder.addFieldInt64(1, placementId, BigInt('0'));
}

static addInstanceOverridesJson(builder:flatbuffers.Builder, instanceOverridesJsonOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, instanceOverridesJsonOffset, 0);
}

static endSetLevelEntityOverridesPayload(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createSetLevelEntityOverridesPayload(builder:flatbuffers.Builder, levelId:bigint, placementId:bigint, instanceOverridesJsonOffset:flatbuffers.Offset):flatbuffers.Offset {
  SetLevelEntityOverridesPayload.startSetLevelEntityOverridesPayload(builder);
  SetLevelEntityOverridesPayload.addLevelId(builder, levelId);
  SetLevelEntityOverridesPayload.addPlacementId(builder, placementId);
  SetLevelEntityOverridesPayload.addInstanceOverridesJson(builder, instanceOverridesJsonOffset);
  return SetLevelEntityOverridesPayload.endSetLevelEntityOverridesPayload(builder);
}
}
